config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>

    <%= render partial: "shared/header" %>
    <%= render partial: "shared/message" %>

    <div class="container">
      <main>
        <%= yield %>
      </main>
    </div>

    <%= render partial: "shared/footer" %>

  </body>

  <script>
    $(".button-collapse").sideNav();
    $(".dropdown-button").dropdown();
  </script>


</html>

app/views/pages/about.html.erb
<h3>About Me</h3>

  <div class="card z-depth-3">
    <div class="card-content white-text">
      <div class="row">

        <div class="col m6">
          <a class="twitter-timeline" data-width="600" data-height="300" href="https://twitter.com/_francis_huang_">Tweets by _francis_huang_</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>

        <div class="col m6">
          <div class="card-panel grey lighten-5 z-depth-1">
            <div class="valign-wrapper">

              <div class="col m3">
                <%= image_tag "avatar.jpg", :class => "circle responsive-img" %>
              </div>

              <div class="col m9">
                <span class="black-text">Hey, this is me. Nice to meet you!</span>
              </div>

            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

app/views/shared/_footer.html.erb
<footer class="page-footer brown lighten-4 z-depth-2">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Code4Pro</h5>
        <p class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur omnis, illo laboriosam sequi, consequuntur aut totam provident ipsam nam, commodi assumenda iure explicabo autem quasi dolor facere eum in delectus!</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Linkedin</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Angellist</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2017 Code4Pro
    <%= link_to "About Me", pages_about_path, :class => "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <li><a href="#!">My Profile</a></li>
    <li><a href="#!">My Courses</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>

  <ul id="dropdown2" class="dropdown-content">
    <li><a href="#!">My Profile</a></li>
    <li><a href="#!">My Courses</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>

  <nav class="brown lighten-4 z-depth-2">
  <div class="container">
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Code4Pro</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Courses</a></li>
        <% if(!user_signed_in?) %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% else %>  <!-- Dropdown Trigger -->
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.email %>
          <i class="material-icons right">arrow_drop_down</i></a></li>
        <% end %>
      </ul>

      <ul class="side-nav" id="mobile-demo">
        <% if(!user_signed_in?) %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% else %>  <!-- Dropdown Trigger -->
          <li><a class="dropdown-button" href="#!" data-activates="dropdown2"><%= current_user.email %>
          <i class="material-icons right">arrow_drop_down</i></a></li>
        <% end %>
      </ul>
    </div>
  </div>
  </nav>
</header>

app/views/shared/_message.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>